# Generated by Django 5.2.7 on 2025-10-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='certification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='certification_earned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completed_lesson_ids',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='progress_data',
            field=models.TextField(default='{}'),
        ),
    ]
