# Generated by Django 5.2.7 on 2025-10-25 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('prompt_writing', 'Prompt Writing Exercise'), ('scenario_analysis', 'AI Use Case Scenario')], max_length=20)),
                ('ai_prompt_template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LearningTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty_level', models.IntegerField(default=1)),
                ('learning_objectives', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='lessons_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GeneratedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('difficulty_adapted', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.contenttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.learningtopic')),
            ],
        ),
        migrations.AddField(
            model_name='contenttemplate',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.learningtopic'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.learningtopic'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'topic')},
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='score',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
